### ISSUE TITLE
classTransformer.plainToClass is not a function

### ISSUE THREAD

**Issue by JotaF93** [SpaceUY/NestJS-Template#1]
Got this error when trying to add class validations in my DTO 

```
import { IsOptional, IsString } from 'class-validator';

export class GetNominaFilterDto {
  @IsOptional()
  @IsString()
  search?: string;
}
```

Found a discussion related to this problem in [this link](https://github.com/typestack/class-validator/issues/1411).
To summarize it is related to the dependency "class-transformer": "^0.4.0".

In my case i downgraded to 0.4.0 to solve the problem.

Here is the log for this error:
```
[Nest] 25352  - 30/06/2022 10:38:01   ERROR [ExceptionsHandler] classTransformer.plainToClass is not a function
TypeError: classTransformer.plainToClass is not a function
    at ValidationPipe.transform (C:\Users\Usuario\Documents\SpaceDev\UTEC\utec-cicd\utec-gu-backend\node_modules\@nestjs\common\pipes\validation.pipe.js:52:39)
    at C:\Users\Usuario\Documents\SpaceDev\UTEC\utec-cicd\utec-gu-backend\node_modules\@nestjs\core\pipes\pipes-consumer.js:16:33
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by nqhd3v** [comment]
Run `yarn add class-transformer@0.5.1`, and your issue should be fixed!
